### ISSUE TITLE
vcdExtra::datasets not working with many Packages

### ISSUE THREAD

**Issue by EduardoJacob** [friendly/vcdExtra#6]
vcdExtra::datasets not working with many Packages like caret or mlbench:
vcdExtra::datasets("caret")
Error in get(x) : object 'GermanCredit' not found

Is this a Bug ?
I'm using R3.6.1, vcdExtra 0.7.1
Thanks

**Comment by dmurdoch** [comment]
I think the `datasets` function implicitly assumes that the package it is listing uses the `LazyData` setting in its description.  The `caret` package doesn't do that.  It is probably fairly easy to fix; I'll see if I can do it.

**Comment by dmurdoch** [comment]
I've added a PR to fix this.

**Comment by friendly** [comment]
Thanks @EduardoJacob for noticing this and to @dmurdoch for the PR. I'll check & test.
`datasets()` is probably more useful than just the `vcdExtra` package, but I don't know where else it could go.

**Comment by friendly** [comment]
Tested: this now works with `vcdExtra::datasets("caret")`
